baseurl: "" # the subpath of your site, e.g. blog/
url: "https://www.bitcraftproduction.com"

title: BitCraft Production
description: >- # this means to ignore newlines until "baseurl:"
  Building creative apps, tools, and games for the future.

disqus_shortname: "" # Add your shortname for Disqus Comment. For example : mr-brown

# Scss Directory
sass:
  sass_dir: assets/scss
  style: compressed

# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll/tagging

paginate: 6
paginate_path: "/page/:num"

# include
include:
  - _pages
  - _authors
  - _es

# Pages Path
defaults:
  - scope:
      path: "_pages"
    values:
      layout: page
      permalink: /:basename:output_ext

  - scope:
      path: "_authors"
    values:
      permalink: /author/:basename:output_ext
      layout: author
      lang: en

  - scope:
      path: "_es"
    values:
      permalink: /es/:basename:output_ext
      layout: post
      lang: es

  - scope:
      path: ""
      type: "posts"
    values:
      permalink: post/:title:output_ext
      layout: post
      lang: en

  # - scope:
  #     path: "es"
  #     type: "posts"
  #   values:
  #     lang: es
  #     permalink: /es/:title/
  #     layout: post
# Tags
tag_page_dir: tag
tag_page_layout: tags
tag_permalink_style: pretty

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
