baseurl: "" 
url: "https://www.bitcraftproduction.com"

title: BitCraft Production
description: >-
  Building creative apps, tools, and games for the future.

disqus_shortname: "" # Optional: add if you use Disqus

sass:
  sass_dir: assets/scss
  style: compressed

# Build settings
markdown: kramdown
permalink: pretty

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll/tagging

paginate: 6
paginate_path: "/page/:num"

# Include custom folders
include:
  - _pages
  - _authors
  - es   # ✅ Add this so Jekyll processes your /es directory if it's not inside _posts or _pages

# Pages and Posts Path Settings
defaults:
  - scope:
      path: "_pages"
    values:
      permalink: /:basename:output_ext

  - scope:
      path: "_authors"
    values:
      permalink: /author/:basename:output_ext
      layout: author

  - scope:
      path: ""
      type: "posts"
    values:
      permalink: /post/:title/
      layout: post
      lang: en

  - scope:
      path: "es"
    values:
      permalink: /es/:title/
      layout: post
      lang: es

# Tags
tag_page_dir: tag
tag_page_layout: tags
tag_permalink_style: pretty

# Exclude from build
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
