title: "BitCraft Production"
description: "Building tools, apps, games, and creative magic."
email: your-email@example.com
timezone: UTC
baseurl: "" # If you're hosting at a subpath, set it like "/myproject"
url: "https://www.bitcraftproduction.com" # Don't forget https!

logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
author: Ganesh Kumar
paginate: 30
disqus: '' # leave blank for now
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
ganalytics: UA-113961478-1

markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true

sass:
  sass_dir: _sass
  style: :compressed

# Plugin Settings
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

# Posts & Pages Path Configs
defaults:
  - scope:
      path: "_pages"
    values:
      permalink: /:basename:output_ext
      layout: page

  - scope:
      path: ""
      type: "posts"
    values:
      permalink: post/:title:output_ext
      layout: post

# Authors (replace or extend as needed)
authors:
  ganesh:
    name: Ganesh Kumar
    display_name: Ganesh Kumar
    avatar: 'assets/images/ganesh.png' # Optional
    email: your-email@example.com
    web: https://www.bitcraftproduction.com
    twitter: https://twitter.com/yourhandle
    description: "Founder of BitCraft Production. Building Study Friend and more."

# Social
social:
  instagram: https://www.instagram.com/yourhandle
  facebook: https://www.facebook.com/yourpage
  twitter: https://twitter.com/yourhandle

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - README.md
